import type { ProfileFieldKey } from '../types/field.ts';

export interface FieldVocabulary {
  key: ProfileFieldKey;
  category: 'personal' | 'education' | 'online' | 'skills';
  canonicalName: string;
  synonyms: string[];
  autocompleteTokens: string[];
  compatibleInputTypes: string[];
  negativeKeywords: string[];
}

/**
 * Centralized vocabulary and semantic definitions for all supported profile fields.
 */
export const FIELD_VOCABULARY: Record<ProfileFieldKey, FieldVocabulary> = {
  'personal.fullName': {
    key: 'personal.fullName',
    category: 'personal',
    canonicalName: 'Full Name',
    synonyms: [
      'full name',
      'fullname',
      'candidate name',
      'applicant name',
      'your name',
      'legal name',
      'complete name',
      'candidate full name',
      'applicant full name',
      'name of candidate',
      'name of applicant',
    ],
    autocompleteTokens: ['name'],
    compatibleInputTypes: ['text'],
    negativeKeywords: [
      'company',
      'organization',
      'employer',
      'father',
      'mother',
      'guardian',
      'emergency',
      'user',
      'username',
      'login',
      'reference',
      'referee',
      'first',
      'last',
      'middle',
      'given',
      'surname',
      'family',
    ],
  },

  'personal.firstName': {
    key: 'personal.firstName',
    category: 'personal',
    canonicalName: 'First Name',
    synonyms: [
      'first name',
      'firstname',
      'given name',
      'forename',
      'first',
      'candidate first name',
      'applicant first name',
    ],
    autocompleteTokens: ['given-name', 'given name'],
    compatibleInputTypes: ['text'],
    negativeKeywords: [
      'company',
      'organization',
      'employer',
      'user',
      'username',
      'father',
      'mother',
      'guardian',
    ],
  },

  'personal.lastName': {
    key: 'personal.lastName',
    category: 'personal',
    canonicalName: 'Last Name',
    synonyms: [
      'last name',
      'lastname',
      'family name',
      'surname',
      'last',
      'candidate last name',
      'applicant last name',
    ],
    autocompleteTokens: ['family-name', 'family name', 'surname'],
    compatibleInputTypes: ['text'],
    negativeKeywords: [
      'company',
      'organization',
      'employer',
      'user',
      'username',
      'father',
      'mother',
      'guardian',
    ],
  },

  'personal.email': {
    key: 'personal.email',
    category: 'personal',
    canonicalName: 'Email Address',
    synonyms: [
      'email',
      'email address',
      'e mail',
      'email id',
      'emailid',
      'e-mail',
      'electronic mail',
      'candidate email',
      'applicant email',
      'personal email',
      'primary email',
    ],
    autocompleteTokens: ['email'],
    compatibleInputTypes: ['email', 'text'],
    negativeKeywords: [
      'company',
      'organization',
      'employer',
      'parent',
      'guardian',
      'emergency',
      'referrer',
      'reference',
    ],
  },

  'personal.phone': {
    key: 'personal.phone',
    category: 'personal',
    canonicalName: 'Phone Number',
    synonyms: [
      'phone',
      'phone number',
      'mobile',
      'mobile number',
      'telephone',
      'contact number',
      'cell phone',
      'cell number',
      'mobile no',
      'phone no',
      'candidate phone',
      'applicant phone',
      'primary phone',
    ],
    autocompleteTokens: ['tel', 'tel-national', 'mobile'],
    compatibleInputTypes: ['tel', 'text', 'number'],
    negativeKeywords: [
      'emergency',
      'company',
      'organization',
      'employer',
      'work',
      'office',
      'fax',
      'parent',
      'guardian',
      'alternate',
      'secondary',
      'reference',
    ],
  },

  'personal.location': {
    key: 'personal.location',
    category: 'personal',
    canonicalName: 'Location',
    synonyms: [
      'location',
      'city',
      'current location',
      'address',
      'residence',
      'current city',
      'city location',
      'living in',
      'based in',
      'home location',
      'current address',
    ],
    autocompleteTokens: ['address-level2', 'street-address', 'country-name'],
    compatibleInputTypes: ['text'],
    negativeKeywords: [
      'job location',
      'preferred location',
      'work location',
      'office location',
      'company location',
      'headquarters',
    ],
  },

  'education.college': {
    key: 'education.college',
    category: 'education',
    canonicalName: 'College / University',
    synonyms: [
      'college',
      'university',
      'institution',
      'educational institution',
      'school/college',
      'school college',
      'university name',
      'college name',
      'campus',
      'institute',
      'alma mater',
      'higher education',
    ],
    autocompleteTokens: ['organization'],
    compatibleInputTypes: ['text'],
    negativeKeywords: ['company', 'employer', 'high school', 'secondary school'],
  },

  'education.degree': {
    key: 'education.degree',
    category: 'education',
    canonicalName: 'Degree',
    synonyms: [
      'degree',
      'qualification',
      'program',
      'course',
      'education level',
      'degree name',
      'degree type',
      'highest degree',
      'educational qualification',
      'level of education',
    ],
    autocompleteTokens: [],
    compatibleInputTypes: ['text', 'select'],
    negativeKeywords: ['temperature', 'angle', 'company', 'branch', 'major', 'specialization'],
  },

  'education.branch': {
    key: 'education.branch',
    category: 'education',
    canonicalName: 'Branch / Major',
    synonyms: [
      'branch',
      'specialization',
      'major',
      'stream',
      'field of study',
      'department',
      'discipline',
      'major subject',
      'course specialization',
      'area of study',
    ],
    autocompleteTokens: [],
    compatibleInputTypes: ['text', 'select'],
    negativeKeywords: ['company branch', 'bank branch', 'office branch'],
  },

  'education.cgpa': {
    key: 'education.cgpa',
    category: 'education',
    canonicalName: 'CGPA / GPA',
    synonyms: [
      'cgpa',
      'gpa',
      'grade point average',
      'percentage',
      'score',
      'grade point',
      'cumulative gpa',
      'marks percentage',
    ],
    autocompleteTokens: [],
    compatibleInputTypes: ['number', 'text'],
    negativeKeywords: ['credit', 'salary', 'experience', 'year'],
  },

  'education.graduationYear': {
    key: 'education.graduationYear',
    category: 'education',
    canonicalName: 'Graduation Year',
    synonyms: [
      'graduation year',
      'graduating year',
      'year of graduation',
      'passing year',
      'completion year',
      'year of passing',
      'grad year',
      'end year',
      'passout year',
      'batch',
    ],
    autocompleteTokens: [],
    compatibleInputTypes: ['number', 'text', 'select'],
    negativeKeywords: ['birth', 'born', 'start year', 'experience', 'joined', 'joining year'],
  },

  'online.github': {
    key: 'online.github',
    category: 'online',
    canonicalName: 'GitHub',
    synonyms: [
      'github',
      'github profile',
      'github url',
      'github link',
      'github username',
      'git profile',
      'github repository',
    ],
    autocompleteTokens: ['url'],
    compatibleInputTypes: ['url', 'text'],
    negativeKeywords: ['company github', 'employer github'],
  },

  'online.linkedin': {
    key: 'online.linkedin',
    category: 'online',
    canonicalName: 'LinkedIn',
    synonyms: [
      'linkedin',
      'linkedin profile',
      'linkedin url',
      'linkedin link',
      'linkedin username',
    ],
    autocompleteTokens: ['url'],
    compatibleInputTypes: ['url', 'text'],
    negativeKeywords: ['company linkedin', 'employer linkedin'],
  },

  'online.portfolio': {
    key: 'online.portfolio',
    category: 'online',
    canonicalName: 'Portfolio',
    synonyms: [
      'portfolio',
      'portfolio website',
      'personal website',
      'website',
      'portfolio url',
      'personal site',
      'portfolio link',
      'blog url',
      'web page',
      'online portfolio',
    ],
    autocompleteTokens: ['url'],
    compatibleInputTypes: ['url', 'text'],
    negativeKeywords: ['company website', 'employer website', 'organization website'],
  },

  'skills': {
    key: 'skills',
    category: 'skills',
    canonicalName: 'Skills',
    synonyms: [
      'skills',
      'technical skills',
      'key skills',
      'technologies',
      'programming skills',
      'core competencies',
      'skillset',
      'tools and technologies',
      'proficiencies',
    ],
    autocompleteTokens: [],
    compatibleInputTypes: ['textarea', 'text'],
    negativeKeywords: ['soft skills', 'interpersonal skills'],
  },
};
